import {
  BarChart3,
  BellRing,
  Building2,
  CalendarClock,
  Database,
  FileText,
  History,
  LayoutDashboard,
  Package,
  ClipboardList,
  Receipt,
  Landmark,
  ShoppingCart,
  Tag,
  UserCircle,
  Users,
  Wallet,
  ClipboardCheck,
  PackageCheck,
  MapPin,
  Bookmark,
  Settings as SettingsIcon,
  Scale,
} from 'lucide-react';

export const sections = [
  {
    title: 'Inicio',
    items: [
      {
        icon: LayoutDashboard,
        label: 'Mi turno',
        path: '/cajero',
        roles: ['CAJERO'],
        badge: { text: 'TURNO', variant: 'live' },
      },
      {
        icon: ShoppingCart,
        label: 'Facturacion POS',
        path: '/facturacion',
        roles: ['CAJERO'],
        permissions: ['SALE_CREATE'],
        badge: { text: 'COBRAR', variant: 'live' },
      },
      {
        icon: LayoutDashboard,
        label: 'Panel consulta',
        path: '/',
        roles: ['CONSULTOR'],
      },
      {
        icon: LayoutDashboard,
        label: 'Panel supervision',
        path: '/',
        roles: ['SUPERVISOR'],
        badge: { text: 'LIVE', variant: 'live' },
      },
      {
        icon: LayoutDashboard,
        label: 'Dashboard',
        path: '/',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        badge: { text: 'LIVE', variant: 'live' },
      },
    ],
  },
  {
    title: 'Operaciones',
    items: [
      {
        icon: ShoppingCart,
        label: 'Facturacion POS',
        path: '/facturacion',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['SALE_CREATE'],
        badge: { text: 'POS', variant: 'live' },
      },
      {
        icon: Users,
        label: 'Clientes',
        path: '/clientes',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
      },
      {
        icon: Receipt,
        label: 'Control de ventas',
        path: '/control-ventas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['SALE_CANCEL'],
      },
      {
        icon: FileText,
        label: 'Facturas Electronicas',
        path: '/facturas-electronicas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['EINVOICE_VIEW'],
        badge: { text: 'DGI', variant: 'new' },
      },
      {
        icon: Wallet,
        label: 'Control de cajas',
        path: '/control-cajas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['CASH_OPEN', 'CASH_MOVE', 'CASH_CLOSE'],
        badge: { text: 'NEW', variant: 'new' },
      },
      {
        icon: ClipboardCheck,
        label: 'Cierre del dia',
        path: '/cierre-dia',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['CASH_CLOSE'],
        badge: { text: 'ACTA', variant: 'new' },
      },
      {
        icon: Landmark,
        label: 'Finanzas',
        path: '/finanzas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['FINANCE_VIEW', 'FINANCE_MANAGE'],
      },
    ],
  },
  {
    title: 'Inventario',
    items: [
      {
        icon: Package,
        label: 'Productos',
        path: '/inventario',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['INVENTORY_ADJUST'],
      },
      {
        icon: CalendarClock,
        label: 'Lotes y vencimientos',
        path: '/lotes',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['INVENTORY_ADJUST'],
        badge: { text: 'PEPS', variant: 'new' },
      },
      {
        icon: Tag,
        label: 'Promociones',
        path: '/promociones',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['PROMO_MANAGE'],
        badge: { text: 'NUEVO', variant: 'new' },
      },
      {
        icon: ClipboardList,
        label: 'Compras',
        path: '/compras',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['PURCHASE_MANAGE', 'PURCHASE_RECEIVE'],
        badge: { text: 'NEW', variant: 'new' },
      },
      {
        icon: Tag,
        label: 'Categorias',
        path: '/categorias',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['INVENTORY_ADJUST'],
      },
      {
        icon: Bookmark,
        label: 'Marcas',
        path: '/marcas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['INVENTORY_ADJUST'],
      },

      {
        icon: Building2,
        label: 'Proveedores',
        path: '/proveedores',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['PURCHASE_MANAGE', 'PURCHASE_RECEIVE'],
      },
    ],
  },
  {
    title: 'Bodega',
    items: [
      {
        icon: PackageCheck,
        label: 'Inicio bodega',
        path: '/bodega',
        roles: ['BODEGUERO'],
        badge: { text: 'HOME', variant: 'live' },
      },
      {
        icon: ClipboardList,
        label: 'Recepcion',
        path: '/bodega/recepcion',
        roles: ['BODEGUERO', 'ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['PURCHASE_RECEIVE'],
        badge: { text: 'SCAN', variant: 'new' },
      },
      {
        icon: CalendarClock,
        label: 'Lotes y vencimientos',
        path: '/lotes',
        roles: ['BODEGUERO'],
        permissions: ['BATCH_MANAGE', 'INVENTORY_ADJUST'],
      },
      {
        icon: Package,
        label: 'Consulta productos',
        path: '/bodega/productos',
        roles: ['BODEGUERO'],
        permissions: ['INVENTORY_VIEW'],
      },
      {
        icon: ClipboardCheck,
        label: 'Conteo ciclico',
        path: '/bodega/conteo',
        roles: ['BODEGUERO', 'ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['INVENTORY_COUNT', 'INVENTORY_ADJUST'],
        badge: { text: 'NEW', variant: 'new' },
      },
      {
        icon: MapPin,
        label: 'Ubicaciones',
        path: '/ubicaciones',
        roles: ['BODEGUERO', 'ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['WAREHOUSE_LOCATION', 'INVENTORY_ADJUST'],
      },
    ],
  },
  {
    title: 'Analitica',
    items: [
      {
        icon: BarChart3,
        label: 'Reportes',
        path: '/reportes',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR', 'CONSULTOR'],
        permissions: ['REPORT_VIEW'],
      },
      {
        icon: BellRing,
        label: 'Alertas',
        path: '/alertas',
        roles: ['BODEGUERO', 'ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR'],
        permissions: ['REPORT_VIEW'],
        badge: { text: 'IA', variant: 'new' },
      },
      {
        icon: History,
        label: 'Auditoria',
        path: '/auditoria',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['AUDIT_VIEW'],
      },
    ],
  },
  {
    title: 'Sistema',
    items: [
      {
        icon: UserCircle,
        label: 'Mi perfil',
        path: '/mi-perfil',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO', 'SUPERVISOR', 'CAJERO', 'CONSULTOR', 'BODEGUERO'],
      },
      {
        icon: Users,
        label: 'Usuarios y roles',
        path: '/usuarios',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['USER_MANAGE'],
      },
      {
        icon: SettingsIcon,
        label: 'Configuracion',
        path: '/configuracion',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['USER_MANAGE'],
      },
      {
        icon: BellRing,
        label: 'Configuración Alertas',
        path: '/configuracion-alertas',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
        permissions: ['USER_MANAGE'],
      },
      {
        icon: Scale,
        label: 'Configuración de Balanza',
        path: '/configuracion-balanza',
        roles: ['ADMINISTRADOR', 'ADMIN_INGENIERO'],
      },
      {
        icon: Database,
        label: 'Mantenimiento',
        path: '/mantenimiento',
        roles: ['ADMIN_INGENIERO'],
        permissions: ['MAINTENANCE_MANAGE'],
      },
    ],
  },
];
